---
galaxy_info:
  author: Jonathan Wright
  description: Configure thunderbolt mesh network for Proxmox nodes
  company: n3tuk
  issue_tracker_url: https://github.com/n3tuk/ansible/issues
  license: MIT
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - proxmox
    - networking
    - thunderbolt

dependencies: []
