---
# arch-specific tasks file for fish on Arch Linux

- name: Install Fish
  community.general.pacman:
    name: "{{ fish_packages_arch }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - fish
    - packages
