---
# debian-specific tasks file for fish

- name: Install fish packages
  ansible.builtin.apt:
    name: "{{ fish_packages_debian }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - fish
    - packages
