---
# arch-specific tasks file for bash

- name: Install Bash
  community.general.pacman:
    name: "{{ bash_packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - bash
    - packages
