---
galaxy_info:
  author: Jonathan Wright
  description: Configure Caddy for Proxmox
  company: n3tuk
  issue_tracker_url: https://github.com/n3tuk/nsible/issues
  license: MIT
  min_ansible_version: "2.20"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - caddy
    - loadbalancer

dependencies: []
