---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        name: Check this commit is not to the main/master branch
      - id: check-merge-conflict
        name: Check for merge conflicts before committing
      - id: check-case-conflict
        name: Check for case conflicts for case-sensitive filesystems
      - id: check-symlinks
        name: Check for broken syslinks in the repository
      - id: destroyed-symlinks
        name: Check for destroyed symlinks in the repository
      - id: check-added-large-files
        name: Check no large files have been added to the commit
      - id: check-json
        name: Check JSON files for correctness
      - id: trailing-whitespace
        name: Check all trailing whitespace is removed
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
        name: Check all files end in a new-line only

  - repo: https://github.com/zricethezav/gitleaks.git
    rev: v8.29.0
    hooks:
      - id: gitleaks
        name: Check for hard-coded secrets, keys, and credentials

  - repo: https://github.com/jumanjihouse/pre-commit-hooks.git
    rev: 3.0.0
    hooks:
      - id: script-must-have-extension
        name: Check non-executable shell scripts end with .sh extension
      - id: script-must-not-have-extension
        name: Check executable shell scripts to not have extension
      - id: shellcheck
        name: Check shell scripts with shellcheck
      - id: shfmt
        name: Check shell scripts formtting with shfmt
        args:
          - -i
          - "2"
          - -bn
          - -ci
          - -sr

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: Lint YAML files for correctness and formatting
        args:
          - --config-file
          - .yamllint.yaml

  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 0.34.1
    hooks:
      - name: Check the Dependabot configuration for correctness
        id: check-dependabot
      - name: Check the GitHub Workflows for correctness
        id: check-github-workflows

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.2
    hooks:
      - id: ansible-lint
        name: Lint Ansible files for correctness and formatting
        files: ^(plays/(encrypted|group|host)_vars/[a-z0-9-\.]+\.yaml|roles/[a-z0-9_]+/(defaults|handlers|meta|tasks|vars)/[a-z0-9-\.]+\.yaml)$
        always_run: false
        additional_dependencies:
          - ansible

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: Check Markdown correctness and formatting
