---
stepca_postgresql_host: "[::1]"

stepca_postgresql_username: stepca
stepca_postgresql_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30303164376331363265626561646639333662656239353737353035326633373533356238356136
  6163393438313365636332326633613539616130326564300a633038663835373035623038633937
  65333065373436653463666430616130303838306362316336373266663563356538363938363132
  3639393636636232390a616164393135366434656534376566663761643666376132336462333839
  31333965613866656161633437613039626234366439646262383161383963326166616139313731
  38336465633535653935366364323566636339323931616531306265353632663534363730623831
  36343666366532643061663037363339363665303436633664333366336663363233616364633535
  66386430373265313837623836326437636665383565346239653939356662656363303736626236
  63633937613338616664353932303061376463613965633662623066326433363366
stepca_postgresql_database: stepca
stepca_yubikey_serial: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64356233336132386130643433633962373464326439353032323766323830316366346263336532
  3963623463633664303965383733666632393932313434320a646538333666363361393864353836
  37646133656366626165306434353730613665663633323035323964373336643332653339666137
  6666333333393433350a633864343837326265373638343633333533343662613463666361366134
  6464
stepca_yubikey_pin: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64636539626137616531333938353731653737333266373061326265326237363236326638356561
  3833393632383239323636376561666334656361383432610a326430313331336264353562346634
  30653438626466353237636537363737313138343866653535623962383664363964383139383862
  6266383365636238610a636237616162646639353933373934396135393963643237646137353163
  3831

stepca_intermediate_ca_id: 2
stepca_intermediate_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIGHTCCBAWgAwIBAgIJAM75YnZb2SUBMA0GCSqGSIb3DQEBDQUAMDoxCzAJBgNV
  BAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNVBAMMEW4zdC51ayBSb290IENB
  IFIxMB4XDTI1MTEyMTAwMDAwMFoXDTMxMDEwMTAwMDAwMFowQjELMAkGA1UEBhMC
  VUsxDzANBgNVBAoMBm4zdC51azEiMCAGA1UEAwwZbjN0LnVrIEludGVybWVkaWF0
  ZSBDQSBDMjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALoNxJQ7/w5P
  XDEny5jjrdqCTqzU+kt2L/PfnaMlI6lthm+suWGNAyS/mfhwT7YgeWKL32Ka/2Vj
  arFuBDEnO+elXuTSkmmnkw9Hg3sFlmYGGR3LKx2ghuTDLhIz+TWqCglePcJkAeRu
  LvEDdwrYRT99NdLgjleGINsTOs5kgEgN85QkwCoyp98JPhP5wKj3dYkHeTt5WrE0
  fG+uMA0g+irf7zIfr3v7SAWs32G/EorI+mwHksdXsMlvvIjQHlo2hALcshRhQXP6
  //GUzne9IzONt1svH4XGgQW8k9g/gZQYL8qTT7Yk6psRcP5D1DImHGKPMhAesKac
  cmcQCTK7n9tdUPIHl3f8r6yVAqgxX6mK8k/in/HP7+UbA/m26E/5pB5NJcRvV7jK
  sAC0uWO1X3cF3v0WvB8wE+UGaTE8gg6c4XyjIsq00g9Z6xv8kznlTA/rIM8lOHXC
  5uLLjTSithcsf1uX+x80Y7yhHFz5VkcNZmaT+pd/BT9+NDD4eBl/utMDh1YwewRb
  RkX9fZg4uk0jF9Jitcb84ZffauJMDU38QhS+IrjM9ZVcwy7lowUwr3Moda/8gOte
  vAIllXZlJ05N7JY97Ary9dT9X8QQ33jJtSq3+M0tNyDyDU97FqqRVsS+yQKBIF34
  D7QsMOC+uh1vdyE9PDN4T1OCxRrP9Yq3AgMBAAGjggEcMIIBGDAdBgNVHQ4EFgQU
  ebzDSjSuKEpGLC08I9EwZ/MwkdIwagYDVR0jBGMwYYAU6YpJFaxpa8EyCXfSgIWF
  s6ARmfChPqQ8MDoxCzAJBgNVBAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNV
  BAMMEW4zdC51ayBSb290IENBIFIxggkAmSlijzrcpS4wOQYIKwYBBQUHAQEELTAr
  MCkGCCsGAQUFBzAChh1odHRwOi8vY2VydHMuY2EubjN0LnVrL2MyLmNydDAsBgNV
  HR8EJTAjMCGgH6AdhhtodHRwOi8vYzIuY2EubjN0LnVrLzEuMC9jcmwwEgYDVR0T
  AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQENBQADggIB
  ACzKvYbznGN2eZjZenqxDQUI9edUrJIb2j24LcY2hh1o/Iv5+XohtVK+3tLk64AO
  zWhZBRjgd1kTNZDmVO3bXlPqD+uBr/sySK9mwiSNCoZEi4NGZS/gT+lkvEWQ0dta
  bijcmIoNS3wn78SSDLa/eaFdBJMcradoTRH81f4mvq9SPONYJ2HvrJKGx52bN9Eg
  A/H2eWlG+9betzeaI+63AiqHQRdn9JvH6fdHn9IDSkXFQ62NT/HSEiQgu2hpRrkM
  ddg0rj4wQvbY6jo+RQt4XGX8lT+jQlYpOf8tchk4u8KZ4DYJyndShi3lGc/LgBuY
  rjf/QPtPADKnyG8tF9d46ZsG3MpAx2FyPCgJxRLmlPXbuj9s0uMmV18g5T0rwIu2
  77kMSgyCKchfxO90gxAGSsjfoaSr7shRrvcrrifVOeGMHKulG1MUXOVqq4ZZMKoa
  dRmzmAAy4wHodQXguOkeEbinnM+SZ9ujgs/NwfqEl3eNF+hzcKE5lKHBIqCBGe94
  mQu1Hf99A/J33HYNK4oAEPJpoSscQmNZPjyQJbfZGqqwGG8WsxKpbYrD/LAEONLG
  kP+wsOEF6xxWa1bANevyBGPRPUQN+3kmec7ycUQCtfTnscg/eSJBHaHXsQPpBCKt
  7pjtrgkHnEkfHR+6HS8KVoNURvQKuFuKsaBj9ydt4t9Q
  -----END CERTIFICATE-----

systemd_networkd_hosts_entries:
  # In order to help step-ca validate the internal services on this host as part
  # of the ACME HTTP-01 challenge process, we need to override the host entries
  # on this server to force the local hostnames to resolve to the system and not
  # to the Tailnet.
  - addresses:
      - "::1"
    hostname: ca.n3t.uk
  - addresses:
      - "::1"
    hostname: c2.ca.n3t.uk
