---
stepca_postgresql_host: "[::1]"

stepca_postgresql_username: stepca
stepca_postgresql_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65646439633435306533613761623431303133623039333539383332303866346166613231326539
  6338646163363861356230656333353366613566373065630a616463316161613334346366333465
  35646437393534336361396333636238666432306333663163303364303539373361663937653334
  3532343533663266640a633233643262626661353163393333653864646237363334306564656265
  31663365623833653331393733383463363833316464323565666561336338663761653831633761
  61366433316333623261366463386333663532666263633437386630366466333135336634396337
  35396466373132623930643466336531643637383962666264333437626563393965663361653063
  33646632316562336332663038353439333061366162323964633833646662663930626238313737
  32373639613331336364373463313639613762613866386131316466383738666432
stepca_postgresql_database: stepca
stepca_yubikey_serial: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33623138653136313037626264616362666162643863626630333732386635326231346439663637
  6434666162393135656238616538393837313461353530640a633430303763613262613561363862
  66383835316632653636663938386366643538643464343130316333386133383732666337303364
  3139353564393134640a623433343232366362393464653431316335383533396538343031313662
  3063
stepca_yubikey_pin: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36633939316234663661383438386239616630623337393265663234663333626137333563366639
  6265663739363561396538366233326430306562393030390a323932653666336566353333366235
  30313339656161643165306563386162656330326639616237313966373763646338383232383865
  3333613839346336390a666430306639343433346466396239613766343866376536613832613631
  3139

stepca_intermediate_ca_id: 1
stepca_intermediate_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIGHTCCBAWgAwIBAgIJAPS65tR+tS0NMA0GCSqGSIb3DQEBDQUAMDoxCzAJBgNV
  BAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNVBAMMEW4zdC51ayBSb290IENB
  IFIxMB4XDTI1MTEyMTAwMDAwMFoXDTMxMDEwMTAwMDAwMFowQjELMAkGA1UEBhMC
  VUsxDzANBgNVBAoMBm4zdC51azEiMCAGA1UEAwwZbjN0LnVrIEludGVybWVkaWF0
  ZSBDQSBDMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAJ8LyWQiIpY6
  0GmCgsNU1RrA99DObc7qyYYR9jCFEIxUXTA+KAu8apgdf9DkWDJsmXXIBlfKkRWH
  /SQUYEqvexHWkp2I/c/Zfj2vmQ/iIb7scu43RUBAvoNUHueE6qfVnC7ftZVQK+3C
  1z3LIlZ0N/u4dlVul8FEdCwFkiBO/GfiQhpX+GFqj89QFFOty8b98HK1OB3lOPOu
  uFGYEONlbVh7k+JEBQTNSOVMOee+ikbemSf05SOjJiasN5ZIF4g06mzuhpOSLCFF
  ibR1NoSBfUW4iEvTXm9hSqNloc7NwiyVbBK6apXnP2Ac1JR5BdEMKj6c+qBoQ6yt
  YJhWLm65TVHkg7VbfcsY0KIWd8s73qjXINXgZb8RvHzCc3pZAqB85TXID4G0zJUw
  OXi6RaJzChTrOTO1rZIwXteBy04aTCc9xRk9FE90+fpQhdIpA5R8eskXV0ed3K8G
  E1nzoGuZI9rWIiA+8jQti149e3W5xmMrlX6rT+He9GoGt449+cyXkMhNxISk9f5i
  spxBlVHFbrLWAqPWhValxl9iiH2YiD6K3SfD0BwXNlGqpcH0Ln5QT95wXCTT/ph2
  0IcWJSNVu58DHpcoYWXL+SQxA+EoSzY52JP41cH79LW+teo4+7rs/rFUB78q3C62
  xrRBSmD9IpFl14ruOE/3ymmmOJgx3vNtAgMBAAGjggEcMIIBGDAdBgNVHQ4EFgQU
  icIVMlyF7XvfXQtVC2vx3+XJAdwwagYDVR0jBGMwYYAU6YpJFaxpa8EyCXfSgIWF
  s6ARmfChPqQ8MDoxCzAJBgNVBAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNV
  BAMMEW4zdC51ayBSb290IENBIFIxggkAmSlijzrcpS4wOQYIKwYBBQUHAQEELTAr
  MCkGCCsGAQUFBzAChh1odHRwOi8vY2VydHMuY2EubjN0LnVrL2MxLmNydDAsBgNV
  HR8EJTAjMCGgH6AdhhtodHRwOi8vYzEuY2EubjN0LnVrLzEuMC9jcmwwEgYDVR0T
  AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQENBQADggIB
  AKgZIxWaUCD8Cx439vkhhllK8kACo3B6VkyXFupeUtS6AdjhKxVwIBP77+Qi9ysF
  /v6Wk253cM8aVkoOTFfmU6xfDHUeLsPUYjbc+8uLI2XBzXBvV6PSAvOSr5ra6di3
  CalqjtDsFkR51kUNJAj1KsT4G8UQc7hu9gC5E4Wy9Q4T4PfBkewKpdiU3JYcMLqj
  Fq5j99cHQCwTDjW1EItNf9pOpcSFRtunYx2cwkOl+sHtXcbkyTMURguiUsgloVme
  zAWJXmL2+QTALuIshYt5JUHbesZ2N0ycUDAdcXZ0o+IAI5/0SWfmiw3TGC2Bry/t
  Iz6T/489czBjqoiQy0W8QV5dN4mJ/64IsGZAz1RrgHcV0wupvEwzd39b8FeO4sUN
  ATUrnuVHw1G2ZSymxWEM+FOpz/GHH/4l4HeMcqMvblYNzDVcaf5uZPYfU32AMVxR
  UPU6b+XHFc3K2Og1i5c55FcjVa0WZk616FqCJF/ADBxVzyaUAf58c2ToO3ACQeWr
  DicRHo8DuIbY+GepSMekWz4h0to+vB5kNekdLSVu+BCfG/Od52uxxR7EwjTQnEN+
  z2LQs1fy/3/rnjys+P/rZM1GUShaeA5gIOqRH8WAN8UY2aC6Vqx5XCgctnO2BfsF
  tvt9uxu3NF6lfDGw/bpCOJxxub1jTEeK8r43f3tANHD6
  -----END CERTIFICATE-----

systemd_networkd_hosts_entries:
  # In order to help step-ca validate the internal services on this host as part
  # of the ACME HTTP-01 challenge process, we need to override the host entries
  # on this server to force the local hostnames to resolve to the system and not
  # to the Tailnet.
  - addresses:
      - "::1"
    hostname: ca.n3t.uk
  - addresses:
      - "::1"
    hostname: certs.ca.n3t.uk
  - addresses:
      - "::1"
    hostname: c1.ca.n3t.uk
