---
bind_rndc_key_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38316461383538626164316264623439623830363361333038303439613732653964636438376236
  6332333837386338323232326635643662383636623831310a383266653461363336333936303734
  65646262356465656363316131343836306665353934353739383038356535343265623866613865
  3866646135306263330a373764396239333034356237636530306666393039333333373939336565
  62306465316239653664306539626164653363663566373234623637643536313531396166613634
  64623737366630656465393139303337336263306461643837313165373238306166613234316135
  63663332656539663465396439306237306533346534653532313334643033383434643536663538
  33356133323963623432333537653035306362323238613432396561656565373564363033386135
  3630
