---
bind_rndc_key_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34656362366330343065363337396136353237363538393735656432343532663061373863613864
  6439393966316364613165646661343531376233373861380a623833656264316237663937373136
  31666363633162656539366232653739376133633738353135343965643439306539353337356535
  3961636531376335300a623038303034663663623061306262363263353565316633633363393166
  36393333633731386439636236306632316639663661656338666164336135353333613366323265
  31373037303066306364373833373464383339316432613862343638363733346532396666653038
  65303738383733656130663133383435656637326236396364316264363235373166343433303531
  64643937386230363432303465646432653233353336613264633232356530616333326638663465
  3535
