---
device_ipv4_address: 172.23.40.254/24
device_ipv4_gateway: 172.23.40.1
device_ipv6_address: 2a02:8010:8006:3a40:be24:11ff:fe22:8b14/64
device_ipv6_gateway: fe80::7a9a:18ff:fe49:b230

tailscale_hostname: proxmox-manager-01
tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32393436313265663839386236386631613339313963663539323866306663663834303436353564
  6439663634636332316136386134633236656264653861320a643466623635343635356134633965
  33623964313361653466333735626264663665306637343430623434333236333934353730613232
  6462633236366536630a343731316331363964366634316636656262363538366132376365666135
  61363662613962343631373362313263306261313962633066333566663834303035663430373630
  36623136353034626137333931396539363932313833323266323131663364623737333233343265
  613866366365313863336436376437656431
