---
device_ipv4_address: 172.23.40.3/24
device_ipv4_gateway: 172.23.40.1
device_ipv6_address: 2a02:8010:8006:3a40::3/64
device_ipv6_gateway: fe80::7a9a:18ff:fe49:b230

networking_loopback_address: fc00::3
networking_openfabric_router_id: 49.0000.0000.0003.00

tailscale_hostname: proxmox-services-02
tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34373665656362346233316563383161313139623136376561353137623062396330323539306531
  3161663139356364376131326432653665373833373032350a646162666639343636313739343632
  32646265663965336366656366356137333331653437376664313863386563623531343630363133
  3132363864373162360a626636653862303766363234646461656463653839633135393134356536
  64393964303936353035626332353866653661306364643966626466643133623539373464343965
  39303733633537643764356336613562363263353666616334613163623365633463376163393165
  653239333039343062333934346437383765
