---
device_ipv4_address: 172.23.35.4/24
device_ipv4_gateway: 172.23.35.1
device_ipv6_address: 2a02:8010:8006:3a35::4/64
device_ipv6_gateway: fe80::7a9a:18ff:fe49:b230

networking_loopback_address: fc00::4
networking_openfabric_router_id: 49.0000.0000.0004.00

tailscale_hostname: proxmox-development-03
tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32373262316638646235356266323039303139303937363639613435613530353462636638653337
  3730333463333264373834303262346463363137633261310a623439383636643231333839303263
  31353861626434303762353339663435366238633566663539316136366565313436663038613865
  6230316261653536320a643362613430383336353931383865666230613862643936633035356333
  31363561396464346234623166323131316564313531666264643438656331356536336535613732
  65393666343934313733363363666134363339353432313662663331643739356139656565663233
  363933303466386333663232383163366634
