---
# defaults file for valkey

valkey_bind:
  - "0.0.0.0"
  - "::"
valkey_port: 6379

valkey_allowed_hosts: []

valkey_cluster_enabled: false
valkey_replication_primary: localhost
valkey_replication_username: replicator
valkey_replication_password: replicator
valkey_is_primary: false

valkey_loglevel: notice
valkey_max_clients: 1000

valkey_tls_enabled: false
valkey_tls_ca_cert_file: /etc/valkey/ca.crt
valkey_tls_cert_file: /etc/valkey/valkey.crt
valkey_tls_key_file: /etc/valkey/valkey.key

valkey_tls_client_cert_file: /etc/valkey/client.crt
valkey_tls_client_key_file: /etc/valkey/client.key

valkey_acl_users: []
# - name: example
#   enabled: true
#   password: examplepassword
#   rules:
#     - '+@all'
#   comment: This is an example user, do not use
