---
# debian-specific tasks file for ssh

- name: Install SSH
  ansible.builtin.apt:
    name: "{{ ssh_packages_debian }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - sshd
    - packages
