---
# tasks file for ufw

- name: Run pre-flight checks
  ansible.builtin.include_tasks:
    file: pre-flight.yaml

- name: Install on Arch Linux
  ansible.builtin.include_tasks:
    file: arch.yaml
  when: >-
    ansible_facts.distribution == 'Archlinux'

- name: Configure the UFW service
  ansible.builtin.include_tasks:
    file: service.yaml

- name: Configure the UFW rules
  ansible.builtin.include_tasks:
    file: rules.yaml
