---
galaxy_info:
  author: Jonathan Wright
  description: |
    Wipe (if present) and (re)create all filesystems for server bootstrapping
  company: n3tuk
  issue_tracker_url: https://github.com/n3tuk/ansible/issues
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - filesystems

dependencies: []
