---
# tasks file for step-ca

- name: Run pre-flight checks
  ansible.builtin.include_tasks:
    file: pre-flight.yaml

- name: Install on Arch Linux
  ansible.builtin.include_tasks:
    file: arch.yaml
  when: >-
    ansible_facts.distribution == 'Archlinux'

- name: Configure step-ca
  ansible.builtin.include_tasks:
    file: configure.yaml

- name: Configure Caddy for step-ca
  ansible.builtin.include_tasks:
    file: caddy.yaml

- name: Set up the step-ca firewall rules
  ansible.builtin.include_tasks:
    file: firewall.yaml

- name: Set up step-ca
  ansible.builtin.include_tasks:
    file: service.yaml
