---
galaxy_info:
  author: Jonathan Wright
  description: Configure the step-ca Certificate Authority server
  company: n3tuk
  issue_tracker_url: https://github.com/n3tuk/ansible/issues
  license: MIT
  min_ansible_version: "2.20"
  platforms:
    - name: ArchLinux
      versions:
        - all

  galaxy_tags:
    - stepca
    - ca

dependencies: []
