---
# arch-specific tasks file for sudo on Arch Linux

- name: Install sudo packages
  community.general.pacman:
    name: "{{ sudo_packages_arch }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - sudo
    - packages
