---
galaxy_info:
  author: Jonathan Wright
  description: Configure the bind Service for DNS
  company: n3tuk
  issue_tracker_url: https://github.com/n3tuk/ansible/issues
  license: MIT
  min_ansible_version: "2.20"
  platforms:
    - name: ArchLinux
      versions:
        - all

  galaxy_tags:
    - bind
    - dns

dependencies: []
