---
env_purpose: ca-node (step-ca)

filesystems_physical_drives:
  - vda
  - vdb

filesystems_volume_groups:
  - name: storage
    partitions:
      - /dev/vda2
  - name: data
    partitions:
      - /dev/vdb1

filesystems_physical_partitions:
  - name: ESP
    device: vda
    number: 1
    path: /efi
    start: 1MiB
    end: 256MiB
    flags:
      - esp
    pv_type: fat32
    fs_type: vfat
    fs_opts: -F 32 -n ESP
  - name: LVM
    device: vda
    number: 2
    start: 256MiB
    end: 100%
    flags:
      - lvm
  - name: LVM
    device: vdb
    number: 1
    start: 1MiB
    end: 100%
    flags:
      - lvm

filesystems_logical_volumes:
  - name: system
    group: storage
    path: /
    size: 8G
    fs_type: ext4
    fs_opts: -L SYSTEM
  - name: swap
    group: storage
    size: 1G
    fs_type: swap
    fs_opts: -L SWAP
  - name: journald
    group: storage
    path: /var/log/journal
    size: 256M
    fs_type: ext4
    fs_opts: -L JOURNALD
    mount_opts:
      - nosuid
  - name: pacman
    group: storage
    path: /var/cache/pacman
    size: 2G
    fs_type: ext4
    fs_opts: -L PACMAN
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: home
    group: storage
    path: /home
    size: 256M
    fs_type: ext4
    fs_opts: -L HOME
    mount_opts:
      - nosuid
      - nodev
  - name: step-ca
    group: data
    path: /var/lib/step-ca
    size: 4G
    fs_type: ext4
    fs_opts: -L STEP-CA
    mount_opts:
      - nosuid
  - name: postgresql
    group: data
    path: /var/lib/postgres
    size: 16G
    fs_type: ext4
    fs_opts: -L POSTGRESQL
    mount_opts:
      - nosuid

stepca_public_hostname: ca.n3t.uk

stepca_acme_provisioner_name: n3tuk
stepca_acme_trusted_roots: "{{ stepca_srv_path }}/r1.crt"

stepca_oidc_provisioner_name: authentik
stepca_oidc_provisioner_endpoint: >-
  https://auth.n3t.uk/application/o/step-ca/.well-known/openid-configuration
stepca_oidc_provisioner_client_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62313031333832333833393731613131653162666264363039623937353461366132646666313733
  3735313239376264333139643131363230623230306465630a316435326165633065346663653165
  63626234313462393062383661646266633564633536613061303939366537333466626633626261
  6334313566313035320a636630326130363864393466333331336636313231616337333233613638
  32666436366430356333653935393364383530323435313833383838353838616464346230303738
  3433393839643463363438323836333166333262383039623732
stepca_oidc_provisioner_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35613130303934663534363765356232343565666236386231663366383965316637363662393162
  3864333039306565636264653261316264653564323664310a303162313834643336373336323966
  65663330303766306664323636356439356364633834626232326362636631663832643933343839
  3532303132363339320a396133393835306333343932643630646134626663653666353265666164
  38633438353833396534353237353562313962343937303730616632643436643231626461383965
  33363163326635376439363962373130396163373862633339363165666533303931656633656330
  65353436316661313461356263346632303266366435346231353862363239383763663932393237
  61656162303238376435356337653163366261363833376334633737313536643430613663346666
  32303834303434333063303961653763386632663734323666386133326166366235393632306663
  63643838646231383036363330353838633766663062336232316665313562623933373731663937
  353435333162353639343738633062333532

stepca_oidc_provisioner_admins:
  - jonathan@n3t.uk
  - jon@than.io

stepca_listen_address: "[::]"

stepca_allowed_hosts: "{{ groups['ca'] | default([]) }}"
stepca_listen_trusted_proxy_cidrs:
  - "127.0.0.1/32"
  - "::1/128"
  # Because we load balance between the two nodes from the nodes themselves,
  # Authentik can see either local host for traffic coming through the current
  # node or the private IP address of the other node if it's being sent to there
  # by Tailscale, therefore ensure that all relevant addresses are trusted.
  # yamllint disable rule:line-length
  - "{{ hostvars['ca-01.services.n3t.uk'].ansible_facts.default_ipv4.address }}/32"
  - "{{ hostvars['ca-01.services.n3t.uk'].ansible_facts.default_ipv6.address }}/128"
  - "{{ hostvars['ca-02.services.n3t.uk'].ansible_facts.default_ipv4.address }}/32"
  - "{{ hostvars['ca-02.services.n3t.uk'].ansible_facts.default_ipv6.address }}/128"
  # yamllint enable rule:line-length

stepca_x509_allow_dns:
  # Localhost addresses for local services
  - localhost
  # Internal/external addresses for services in n3t.uk and kub3.uk
  - "*.n3t.uk"
  - "ca.n3t.uk"
  - "*.ca.n3t.uk"
  - "*.services.n3t.uk"
  - "*.kub3.uk"
  - "*.development.kub3.uk"
  - "*.production.kub3.uk"
  # Tailscale Tailnet addresses and custom domain
  - "*.icefish-vibe.ts.net"
stepca_x509_allow_email:
  - "@n3t.uk"
  - "@than.io"
stepca_x509_allow_ip:
  # Localhost addresses for local services
  - "::1"
  - "127.0.0.1/32"
  # Internal/external addresses for services in n3t.uk and kub3.uk
  - "2a02:8010:8006::/48"
  - "172.23.0.0/16"
  - "172.27.0.0/16"
  # Tailscale Tailnet addresses and custom domain
  - "fd7a:115c:a1e0::/48"
  - "100.64.0.0/10"

tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63386563396134333265613966313032643537633237353262376434313336666431633164663764
  3732393036633332366365313435623939346263363965380a656438383061616562303162376537
  39633830396666623763313631626664353133386564633761313532653365303035363035643761
  3232373536346137380a666566366333663638666230626134346336303037303266356663393132
  31636435636539343431313138363561636639303835646364346430643336376166393561353436
  63336561326233373934393739633233353564303837323839623064636366303666366562393135
  333064326135393337633632646265383264

postgresql_replication_role: standalone

postgresql_walg_enabled: true
postgresql_walg_aws_region: eu-west-2
postgresql_walg_aws_access_key_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66316639613332313334383238373031313462613436626532316561646263353565336532383434
  3835393464356363376161313739623937333364363039390a663233356234363764323265636235
  38643731333764356263633233623064343830376233396361636632643939633762353663333233
  3864336133303632640a633033666134643435383863636630613761623033356264653237323733
  63336632643539653336376161323662323762636165396463643965386162663137
postgresql_walg_aws_secret_access_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64393931313663373065666436316438373038376636353433363139353766363731396561653232
  6334323532633737663139633862316132386335653037350a623435623961633732653561643736
  38633537663430303733326531333631336236393961633564623366393139306664386637383935
  3738353632343832370a646531663432623764663464363962646434336365633439386533366466
  63663864343836326562306461346633343161343334613363653864316333643662626136353632
  6562303237653365346235313065343864313764646337323237
postgresql_walg_aws_s3_prefix: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64323233336366623036386663666434313430633230656665363038346536393766353238623732
  6238316265333133383337393235346333663433646235640a366538303433336264313461316638
  61356462313930663338623766643564376339623462623934313666383235633637663961383064
  3637633665633132360a373830643331653431356533376434663736326164623432373065633166
  37333434663738306339373665383732633332353062333366623263363036346238653734343866
  31653065616661353961653737333834643737393031316230363635343864363961333633336265
  326566646661393338333861383465313363

stepca_root_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIFNDCCAxygAwIBAgIJAJkpYo863KUuMA0GCSqGSIb3DQEBDQUAMDoxCzAJBgNV
  BAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNVBAMMEW4zdC51ayBSb290IENB
  IFIxMB4XDTI1MTEyMTAwMDAwMFoXDTQwMDEwMTAwMDAwMFowOjELMAkGA1UEBhMC
  VUsxDzANBgNVBAoMBm4zdC51azEaMBgGA1UEAwwRbjN0LnVrIFJvb3QgQ0EgUjEw
  ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCoQ8Cj5CvAFxmB2In3pm5Q
  hWCZ0TY3WTEb27cw/6dSEat8y03fpkEzLJ9ihsZtkoD4sWLF49LjVobOCbAGSWpI
  rhUtVGs86SE7bQAficvYpPPI9VXIOgDHlUOoz3VMy/x1p3QOwX4MMETeOsjG60D9
  WmO+6G8aSJaFxY1gwp6UDxFP4bVmFlwYARVj/KWeM1en1ePTKjGaXZZCCdzolOhQ
  EuzFYxbSrWmqEr5k1ruJ2Qto8mHJaBNuBeqboV/J0Nixtfzc48SGMUcMTBm43oIm
  g2V4OUCfiR7d9a25Gk9QtMPCyQa9MT4uVtFG89SKW/JTDinuMKZrLUQEuymY5KZH
  KKSLczxk9MZAqIJ+jcNOgahq87HLnFVlFcTOayZMBcf/amQOZbDk55gkq567OK24
  8qx2XYR3yzjK64R9qdUGvOeUnxyqEDCld4qKsp8U06X8XAmnEotROPL1CpVviPfn
  GT84EfRG6MMzcFANqme1IL7rd+6ExEZy8FiZgfZlfMmp+Xw/ieQtb/wzbQf+yKhx
  lZP5OdeRu1tP/jatCroSYY+uR1WEtuKw0Q/jEGPdy98faQpS8dXJMGYt/c/ELoT9
  s8y7T4xK4rU4lJvVPu3wX2P5nQ/OgKqw8iJ/d5Bvil3YqIVb4ayvHRRtsBn4FPCs
  0ionK7ON0mf6jBnq3iGPWwIDAQABoz0wOzAdBgNVHQ4EFgQU6YpJFaxpa8EyCXfS
  gIWFs6ARmfAwCQYDVR0jBAIwADAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEB
  DQUAA4ICAQBfj4NdbuJnshhcdqKUTK/g+KxdkjiYGx4rvejMKfCrHtQANx38ZRea
  Z6AXoUkHmyZWOsLYMOzr8buOf6f7/ii0kudQMrTT1CD1MKwFvSqrQoZFNDYqzeOP
  ToCPckHFOd5cSXCsG6Fu8LuyS/7OWycD7WxibrHPdVEzTcfdve3zK4B+QZRk+5Nm
  gWZFF0M5+aZy6i1G4Eujw/hFdHGubuhUxBbsNmiVpDMecPPdTd+q9SuZ7g7ApYzW
  LS/H2FxWrRhXFTRbZ2veXFNw/SWyVXnJfbGlfVa+//ezFa/3b2pkgQfTwRr5F4fS
  2Zfm9RrnPb5n2YihI1anZstkounwq05xfp6915ORf/9pHnlPJymg5F3P2HRQaVIl
  jIZPhF/r+3qjVnnydoWti5LH5Rs71qsVcBtxafB+gld4XJNb9XknHJCZP8AhgxK1
  2Zg3XucmvspMf41iD29GHkl5tNqQ48wkEYihxOf710Q8UCRp7ArkR817LBMXRULk
  XuNhT9iN6vY80hKX6gWXSVUyz80K9EXPXNJXrp5gJBKbhzaDoNt6r+30GsAU0wqr
  5LZTDPj6YEAzYpxGWBqCETqZTQSUQswzN2aC5xdMt/x8iHtQENnYdPkDpbU6J9w+
  Fo5EopJEyYkUaC3Rxby70f+f65mv8yGAg64fy8a/SzAbkehAKs6Yeg==
  -----END CERTIFICATE-----

# We are required to operate some services over HTTP for RFC compliance for
# access to both the Certificate Authority certificates and the Certificate
# Revocation List (CRL). Therefore, we disable automatic HTTPS redirects to
# allow us to run proxies and file servers on port 80, and manually redirect as
# needed to the appropriate services.
caddy_auto_https: disable_redirects

stepca_caddy_serve_certificates:
  r1.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIFNDCCAxygAwIBAgIJAJkpYo863KUuMA0GCSqGSIb3DQEBDQUAMDoxCzAJBgNV
    BAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNVBAMMEW4zdC51ayBSb290IENB
    IFIxMB4XDTI1MTEyMTAwMDAwMFoXDTQwMDEwMTAwMDAwMFowOjELMAkGA1UEBhMC
    VUsxDzANBgNVBAoMBm4zdC51azEaMBgGA1UEAwwRbjN0LnVrIFJvb3QgQ0EgUjEw
    ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCoQ8Cj5CvAFxmB2In3pm5Q
    hWCZ0TY3WTEb27cw/6dSEat8y03fpkEzLJ9ihsZtkoD4sWLF49LjVobOCbAGSWpI
    rhUtVGs86SE7bQAficvYpPPI9VXIOgDHlUOoz3VMy/x1p3QOwX4MMETeOsjG60D9
    WmO+6G8aSJaFxY1gwp6UDxFP4bVmFlwYARVj/KWeM1en1ePTKjGaXZZCCdzolOhQ
    EuzFYxbSrWmqEr5k1ruJ2Qto8mHJaBNuBeqboV/J0Nixtfzc48SGMUcMTBm43oIm
    g2V4OUCfiR7d9a25Gk9QtMPCyQa9MT4uVtFG89SKW/JTDinuMKZrLUQEuymY5KZH
    KKSLczxk9MZAqIJ+jcNOgahq87HLnFVlFcTOayZMBcf/amQOZbDk55gkq567OK24
    8qx2XYR3yzjK64R9qdUGvOeUnxyqEDCld4qKsp8U06X8XAmnEotROPL1CpVviPfn
    GT84EfRG6MMzcFANqme1IL7rd+6ExEZy8FiZgfZlfMmp+Xw/ieQtb/wzbQf+yKhx
    lZP5OdeRu1tP/jatCroSYY+uR1WEtuKw0Q/jEGPdy98faQpS8dXJMGYt/c/ELoT9
    s8y7T4xK4rU4lJvVPu3wX2P5nQ/OgKqw8iJ/d5Bvil3YqIVb4ayvHRRtsBn4FPCs
    0ionK7ON0mf6jBnq3iGPWwIDAQABoz0wOzAdBgNVHQ4EFgQU6YpJFaxpa8EyCXfS
    gIWFs6ARmfAwCQYDVR0jBAIwADAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEB
    DQUAA4ICAQBfj4NdbuJnshhcdqKUTK/g+KxdkjiYGx4rvejMKfCrHtQANx38ZRea
    Z6AXoUkHmyZWOsLYMOzr8buOf6f7/ii0kudQMrTT1CD1MKwFvSqrQoZFNDYqzeOP
    ToCPckHFOd5cSXCsG6Fu8LuyS/7OWycD7WxibrHPdVEzTcfdve3zK4B+QZRk+5Nm
    gWZFF0M5+aZy6i1G4Eujw/hFdHGubuhUxBbsNmiVpDMecPPdTd+q9SuZ7g7ApYzW
    LS/H2FxWrRhXFTRbZ2veXFNw/SWyVXnJfbGlfVa+//ezFa/3b2pkgQfTwRr5F4fS
    2Zfm9RrnPb5n2YihI1anZstkounwq05xfp6915ORf/9pHnlPJymg5F3P2HRQaVIl
    jIZPhF/r+3qjVnnydoWti5LH5Rs71qsVcBtxafB+gld4XJNb9XknHJCZP8AhgxK1
    2Zg3XucmvspMf41iD29GHkl5tNqQ48wkEYihxOf710Q8UCRp7ArkR817LBMXRULk
    XuNhT9iN6vY80hKX6gWXSVUyz80K9EXPXNJXrp5gJBKbhzaDoNt6r+30GsAU0wqr
    5LZTDPj6YEAzYpxGWBqCETqZTQSUQswzN2aC5xdMt/x8iHtQENnYdPkDpbU6J9w+
    Fo5EopJEyYkUaC3Rxby70f+f65mv8yGAg64fy8a/SzAbkehAKs6Yeg==
    -----END CERTIFICATE-----
  c1.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIGHTCCBAWgAwIBAgIJAPS65tR+tS0NMA0GCSqGSIb3DQEBDQUAMDoxCzAJBgNV
    BAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNVBAMMEW4zdC51ayBSb290IENB
    IFIxMB4XDTI1MTEyMTAwMDAwMFoXDTMxMDEwMTAwMDAwMFowQjELMAkGA1UEBhMC
    VUsxDzANBgNVBAoMBm4zdC51azEiMCAGA1UEAwwZbjN0LnVrIEludGVybWVkaWF0
    ZSBDQSBDMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAJ8LyWQiIpY6
    0GmCgsNU1RrA99DObc7qyYYR9jCFEIxUXTA+KAu8apgdf9DkWDJsmXXIBlfKkRWH
    /SQUYEqvexHWkp2I/c/Zfj2vmQ/iIb7scu43RUBAvoNUHueE6qfVnC7ftZVQK+3C
    1z3LIlZ0N/u4dlVul8FEdCwFkiBO/GfiQhpX+GFqj89QFFOty8b98HK1OB3lOPOu
    uFGYEONlbVh7k+JEBQTNSOVMOee+ikbemSf05SOjJiasN5ZIF4g06mzuhpOSLCFF
    ibR1NoSBfUW4iEvTXm9hSqNloc7NwiyVbBK6apXnP2Ac1JR5BdEMKj6c+qBoQ6yt
    YJhWLm65TVHkg7VbfcsY0KIWd8s73qjXINXgZb8RvHzCc3pZAqB85TXID4G0zJUw
    OXi6RaJzChTrOTO1rZIwXteBy04aTCc9xRk9FE90+fpQhdIpA5R8eskXV0ed3K8G
    E1nzoGuZI9rWIiA+8jQti149e3W5xmMrlX6rT+He9GoGt449+cyXkMhNxISk9f5i
    spxBlVHFbrLWAqPWhValxl9iiH2YiD6K3SfD0BwXNlGqpcH0Ln5QT95wXCTT/ph2
    0IcWJSNVu58DHpcoYWXL+SQxA+EoSzY52JP41cH79LW+teo4+7rs/rFUB78q3C62
    xrRBSmD9IpFl14ruOE/3ymmmOJgx3vNtAgMBAAGjggEcMIIBGDAdBgNVHQ4EFgQU
    icIVMlyF7XvfXQtVC2vx3+XJAdwwagYDVR0jBGMwYYAU6YpJFaxpa8EyCXfSgIWF
    s6ARmfChPqQ8MDoxCzAJBgNVBAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNV
    BAMMEW4zdC51ayBSb290IENBIFIxggkAmSlijzrcpS4wOQYIKwYBBQUHAQEELTAr
    MCkGCCsGAQUFBzAChh1odHRwOi8vY2VydHMuY2EubjN0LnVrL2MxLmNydDAsBgNV
    HR8EJTAjMCGgH6AdhhtodHRwOi8vYzEuY2EubjN0LnVrLzEuMC9jcmwwEgYDVR0T
    AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQENBQADggIB
    AKgZIxWaUCD8Cx439vkhhllK8kACo3B6VkyXFupeUtS6AdjhKxVwIBP77+Qi9ysF
    /v6Wk253cM8aVkoOTFfmU6xfDHUeLsPUYjbc+8uLI2XBzXBvV6PSAvOSr5ra6di3
    CalqjtDsFkR51kUNJAj1KsT4G8UQc7hu9gC5E4Wy9Q4T4PfBkewKpdiU3JYcMLqj
    Fq5j99cHQCwTDjW1EItNf9pOpcSFRtunYx2cwkOl+sHtXcbkyTMURguiUsgloVme
    zAWJXmL2+QTALuIshYt5JUHbesZ2N0ycUDAdcXZ0o+IAI5/0SWfmiw3TGC2Bry/t
    Iz6T/489czBjqoiQy0W8QV5dN4mJ/64IsGZAz1RrgHcV0wupvEwzd39b8FeO4sUN
    ATUrnuVHw1G2ZSymxWEM+FOpz/GHH/4l4HeMcqMvblYNzDVcaf5uZPYfU32AMVxR
    UPU6b+XHFc3K2Og1i5c55FcjVa0WZk616FqCJF/ADBxVzyaUAf58c2ToO3ACQeWr
    DicRHo8DuIbY+GepSMekWz4h0to+vB5kNekdLSVu+BCfG/Od52uxxR7EwjTQnEN+
    z2LQs1fy/3/rnjys+P/rZM1GUShaeA5gIOqRH8WAN8UY2aC6Vqx5XCgctnO2BfsF
    tvt9uxu3NF6lfDGw/bpCOJxxub1jTEeK8r43f3tANHD6
    -----END CERTIFICATE-----
  c2.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIGHTCCBAWgAwIBAgIJAM75YnZb2SUBMA0GCSqGSIb3DQEBDQUAMDoxCzAJBgNV
    BAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNVBAMMEW4zdC51ayBSb290IENB
    IFIxMB4XDTI1MTEyMTAwMDAwMFoXDTMxMDEwMTAwMDAwMFowQjELMAkGA1UEBhMC
    VUsxDzANBgNVBAoMBm4zdC51azEiMCAGA1UEAwwZbjN0LnVrIEludGVybWVkaWF0
    ZSBDQSBDMjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALoNxJQ7/w5P
    XDEny5jjrdqCTqzU+kt2L/PfnaMlI6lthm+suWGNAyS/mfhwT7YgeWKL32Ka/2Vj
    arFuBDEnO+elXuTSkmmnkw9Hg3sFlmYGGR3LKx2ghuTDLhIz+TWqCglePcJkAeRu
    LvEDdwrYRT99NdLgjleGINsTOs5kgEgN85QkwCoyp98JPhP5wKj3dYkHeTt5WrE0
    fG+uMA0g+irf7zIfr3v7SAWs32G/EorI+mwHksdXsMlvvIjQHlo2hALcshRhQXP6
    //GUzne9IzONt1svH4XGgQW8k9g/gZQYL8qTT7Yk6psRcP5D1DImHGKPMhAesKac
    cmcQCTK7n9tdUPIHl3f8r6yVAqgxX6mK8k/in/HP7+UbA/m26E/5pB5NJcRvV7jK
    sAC0uWO1X3cF3v0WvB8wE+UGaTE8gg6c4XyjIsq00g9Z6xv8kznlTA/rIM8lOHXC
    5uLLjTSithcsf1uX+x80Y7yhHFz5VkcNZmaT+pd/BT9+NDD4eBl/utMDh1YwewRb
    RkX9fZg4uk0jF9Jitcb84ZffauJMDU38QhS+IrjM9ZVcwy7lowUwr3Moda/8gOte
    vAIllXZlJ05N7JY97Ary9dT9X8QQ33jJtSq3+M0tNyDyDU97FqqRVsS+yQKBIF34
    D7QsMOC+uh1vdyE9PDN4T1OCxRrP9Yq3AgMBAAGjggEcMIIBGDAdBgNVHQ4EFgQU
    ebzDSjSuKEpGLC08I9EwZ/MwkdIwagYDVR0jBGMwYYAU6YpJFaxpa8EyCXfSgIWF
    s6ARmfChPqQ8MDoxCzAJBgNVBAYTAlVLMQ8wDQYDVQQKDAZuM3QudWsxGjAYBgNV
    BAMMEW4zdC51ayBSb290IENBIFIxggkAmSlijzrcpS4wOQYIKwYBBQUHAQEELTAr
    MCkGCCsGAQUFBzAChh1odHRwOi8vY2VydHMuY2EubjN0LnVrL2MyLmNydDAsBgNV
    HR8EJTAjMCGgH6AdhhtodHRwOi8vYzIuY2EubjN0LnVrLzEuMC9jcmwwEgYDVR0T
    AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZIhvcNAQENBQADggIB
    ACzKvYbznGN2eZjZenqxDQUI9edUrJIb2j24LcY2hh1o/Iv5+XohtVK+3tLk64AO
    zWhZBRjgd1kTNZDmVO3bXlPqD+uBr/sySK9mwiSNCoZEi4NGZS/gT+lkvEWQ0dta
    bijcmIoNS3wn78SSDLa/eaFdBJMcradoTRH81f4mvq9SPONYJ2HvrJKGx52bN9Eg
    A/H2eWlG+9betzeaI+63AiqHQRdn9JvH6fdHn9IDSkXFQ62NT/HSEiQgu2hpRrkM
    ddg0rj4wQvbY6jo+RQt4XGX8lT+jQlYpOf8tchk4u8KZ4DYJyndShi3lGc/LgBuY
    rjf/QPtPADKnyG8tF9d46ZsG3MpAx2FyPCgJxRLmlPXbuj9s0uMmV18g5T0rwIu2
    77kMSgyCKchfxO90gxAGSsjfoaSr7shRrvcrrifVOeGMHKulG1MUXOVqq4ZZMKoa
    dRmzmAAy4wHodQXguOkeEbinnM+SZ9ujgs/NwfqEl3eNF+hzcKE5lKHBIqCBGe94
    mQu1Hf99A/J33HYNK4oAEPJpoSscQmNZPjyQJbfZGqqwGG8WsxKpbYrD/LAEONLG
    kP+wsOEF6xxWa1bANevyBGPRPUQN+3kmec7ycUQCtfTnscg/eSJBHaHXsQPpBCKt
    7pjtrgkHnEkfHR+6HS8KVoNURvQKuFuKsaBj9ydt4t9Q
    -----END CERTIFICATE-----
