---
env_name: development
env_colour: yellow

caddy_acme_cloudflare_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66316131666363376232396339373239653063633838373837306231643031653537383466353632
  6130643430383638653532323033313762616335323165390a373763633465626532623936626439
  62363761626362386561373239333231646162303234356339313761366664666434623562356137
  3133393562373934300a313537666666376265303165656362306665643861316133616231313336
  66343764666635396162353939663363356537383462343133363931313239386633653231653837
  3261623735313532646539366430613534386565323333626365
