---
env_name: production
env_colour: red

caddy_acme_cloudflare_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63373931623165613738653835303130633835333061346364386133666362313961376463613362
  3565643939663961323233653935356438346434383932320a383261616136663462333438386532
  38623930353162653932313733633365663039396536663262666138393433303362316236313561
  3164346464353664610a313131386363663561613265653064373939376637396631326265366366
  38376333633765393465613665306638326431336531653063616162636434666165323439386333
  3963393734613937363136666432313461643663356231393633
