---
# defaults file for postgresql

postgresql_allowed_hosts: []
postgresql_replication_hosts: []

postgresql_listen_addresses:
  - "*"
postgresql_port: 5432

postgresql_tls_enabled: false
postgresql_tls_bootstrap: false
# Path to the CA certificate bundle. This default is for Arch Linux. For other
# distributions, it will need to be set explicitly to the appropriate path. For
# example:
#   - /etc/ssl/certs/ca-certificates.crt for Debian/Ubuntu,
#   - /etc/pki/tls/certs/ca-bundle.crt for Red Hat/CentOS
postgresql_tls_ca_crt: /etc/ssl/certs/ca-certificates.crt

postgresql_max_connections: 100

postgresql_replication_role: standalone
postgresql_replication_username: replicator
postgresql_replication_password: replicator

postgresql_pg_hba_entries: []
# - type: host
#   database: replication
#   user: replicator
#   address: 0.0.0.0/0
#   method: scram-sha-256

postgresql_walg_enabled: false
postgresql_walg_version: "3.0.7"
postgresql_walg_aws_region: us-east-1
postgresql_walg_aws_access_key_id: ""
postgresql_walg_aws_secret_access_key: ""
postgresql_walg_aws_s3_prefix: ""
