---
# tasks file for authentik

- name: Run pre-flight checks
  ansible.builtin.include_tasks:
    file: pre-flight.yaml

- name: Install on Arch Linux
  ansible.builtin.include_tasks:
    file: arch.yaml
  when: >-
    ansible_facts.distribution == 'Archlinux'

- name: Configure Caddy for Authentik
  ansible.builtin.include_tasks:
    file: configure.yaml

- name: Set up the Authentik firewall rules
  ansible.builtin.include_tasks:
    file: firewall.yaml

- name: Set up Authentik
  ansible.builtin.include_tasks:
    file: service.yaml
