---
# arch-specific tasks file for bind

- name: Install BIND
  community.general.pacman:
    name: "{{ bind_packages_arch }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - bind
    - packages
