---
galaxy_info:
  author: Jonathan Wright
  description: Install and configure Starship
  company: n3tuk
  issue_tracker_url: https://github.com/n3tuk/ansible/issues
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - starship

dependencies: []
